/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hp
 */

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.util.List;

public class MainJTunes extends JFrame {

    private final JTunes jTunes;
    private ImageIcon ImagenSeleccionada;
    
    /**
     * Creates new form MainJTunes
     */
    public MainJTunes() {
        initComponents();
        jTunes = new JTunes(50);
        AreaCancionesTxt.setText("==== LISTA DE CANCIONES ====\n\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTunesLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CodigoTxt = new javax.swing.JTextField();
        NombreTxt = new javax.swing.JTextField();
        PrecioTxt = new javax.swing.JTextField();
        BtnSeleccionar = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaCancionesTxt = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        CalificarCancionTxt = new javax.swing.JTextField();
        EstrellasCmb = new javax.swing.JComboBox<>();
        BtnCalificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTunesLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JTunesLbl.setText("JTunes: ");

        jLabel1.setText("Codigo: ");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Precio: ");

        BtnSeleccionar.setText("Seleccionar Imagen");
        BtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionarActionPerformed(evt);
            }
        });

        BtnAgregar.setText("Agregar Cancion");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Canciones: ");

        AreaCancionesTxt.setEditable(false);
        AreaCancionesTxt.setColumns(20);
        AreaCancionesTxt.setRows(5);
        jScrollPane1.setViewportView(AreaCancionesTxt);

        jLabel5.setText("Calificar Cancion: ");

        EstrellasCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        BtnCalificar.setText("Calificar");
        BtnCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(PrecioTxt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombreTxt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CodigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JTunesLbl))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnSeleccionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAgregar)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 325, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CalificarCancionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(EstrellasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCalificar)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(JTunesLbl)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CodigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PrecioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSeleccionar)
                    .addComponent(BtnAgregar))
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CalificarCancionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EstrellasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCalificar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionarActionPerformed
        // TODO add your handling code here:
        JFileChooser FileChooser = new JFileChooser();
        FileNameExtensionFilter Filter = new FileNameExtensionFilter("Imagenes", "jpg", "png", "gif");
        FileChooser.setFileFilter(Filter);
        
        if (FileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File Archivo = FileChooser.getSelectedFile();
            ImagenSeleccionada = new ImageIcon(Archivo.getAbsolutePath());
            JOptionPane.showMessageDialog(this, "Imagen seleccionada: " + Archivo.getName());
        }
    }//GEN-LAST:event_BtnSeleccionarActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        // TODO add your handling code here:
        try {
            int Codigo = Integer.parseInt(CodigoTxt.getText());
            String Nombre = NombreTxt.getText();
            double Precio = Double.parseDouble(PrecioTxt.getText());
            
            if (Nombre.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El nombre no puede estar vacio");
                return;
            }
            
            boolean Agregado = jTunes.AddSong(Codigo, Nombre, Precio, ImagenSeleccionada);
            
            if (Agregado) {
                JOptionPane.showMessageDialog(this, "Cancion agregada exitosamente");
                LimpiarFormulario();
                ActualizarLista();
            } else {
                JOptionPane.showMessageDialog(this, "Error: Codigo duplicado o lista llena");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese numeros validos");
        }
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalificarActionPerformed
        // TODO add your handling code here:
        try {
            int Codigo = Integer.parseInt(CalificarCancionTxt.getText());
            
            String EstrellasStr = (String) EstrellasCmb.getSelectedItem();
            int Estrellas = Integer.parseInt(EstrellasStr);
            
            Song Cancion = jTunes.SearchSong(Codigo);
            if (Cancion != null) {
                jTunes.RateSong(Codigo, Estrellas);
                JOptionPane.showMessageDialog(this, "Calificacion agregada");
                ActualizarLista();
                CalificarCancionTxt.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Cancion no encontrada");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Codigo invalido");
        }
    }//GEN-LAST:event_BtnCalificarActionPerformed

    private void LimpiarFormulario() {
        CodigoTxt.setText("");
        NombreTxt.setText("");
        PrecioTxt.setText("");
        ImagenSeleccionada = null;
    }
    
    private void ActualizarLista() {
        StringBuilder Texto = new StringBuilder("==== LISTA DE CANCIONES ====\n\n");
        List<Song> Canciones = jTunes.getAllSongs();
        
        for (Song Cancion : Canciones) {
            Texto.append("==================================\n");
            Texto.append("Codigo: ").append(Cancion.getCodigo()).append("\n");
            Texto.append("Precio: $").append(String.format("%.2f", Cancion.getPrecio()));
            Texto.append(" Rating: ").append(String.format("%.1f", Cancion.SongRating())).append("★");
            Texto.append(Cancion.getImagenDisco() != null ? " [CON IMAGEN] " : " [SIN IMAGEN] ");
            Texto.append("\n\n");
        }
        
        if (Canciones.isEmpty()) {
            Texto.append("No hay canciones ingrsadas aun.\n");
        }
        
        Texto.append("\n---Para calificar: Ingrse el codigo arriba ---");
        AreaCancionesTxt.setText(Texto.toString());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJTunes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJTunes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJTunes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJTunes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainJTunes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaCancionesTxt;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnCalificar;
    private javax.swing.JButton BtnSeleccionar;
    private javax.swing.JTextField CalificarCancionTxt;
    private javax.swing.JTextField CodigoTxt;
    private javax.swing.JComboBox<String> EstrellasCmb;
    private javax.swing.JLabel JTunesLbl;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JTextField PrecioTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
